version: "2"
services:
  test:
    container_name: test
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - firefox
      - chrome
    volumes:
      - ./test:/test
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json

  firefox:
    image: selenium/node-firefox:3.12.0-americium
    shm_size: 2g
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.12.0-americium
    shm_size: 2g
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: hub
    image: selenium/hub:3.12.0-americium
    ports:
      - "4444:4444"