version: "3"
services:
  webdriverio:
    container_name: wdio
    image: wdio_image
    build: .
    depends_on:
      - firefox
      - chrome
      - hub
    volumes:
      - ./:/wdio
    command: npm run test 

  firefox:
    container_name: firefox
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  chrome:
    container_name: chrome
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  hub:
    container_name: hub
    image: selenium/hub
    ports:
      - "4444:4444"