version: "3"
services:
  webdriverio:
    image: "allthings/wdio"
    build: .
    depends_on:
      - firefox
      - chrome
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    command: npm test

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  hub:
    container_name: hub
    image: selenium/hub
    ports:
      - "4444:4444"