version: "3"
services:
  webdriverio:
    container_name: wdio
    image: wdio_image
    build: .
    depends_on:
      - firefox
      - chrome
      - hub
    
    command: >
          bash -c "./wait-for-it.sh --timeout=0 hub:4444 
          && ./wait-for-it.sh --timeout=0 firefox:5555
          && ./wait-for-it.sh --timeout=0 chrome:5555
          && npm run test
          "

  firefox:
    container_name: firefox
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    ports:
      - 5555

  chrome:
    container_name: chrome
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    ports:
      - 5555

  hub:
    container_name: hub
    image: selenium/hub
    ports:
      - "4444:4444"